# Flexget config documentation https://flexget.com/InstallWizard/Linux/Scheduling

variables: flexget-variables.yml

templates:
  anchors:
    _transmission: &transmission
      host: '{? transmission.host ?}'
      port: '{? transmission.port ?}'
      username: '{? transmission.username ?}'
      password: '{? transmission.password ?}'

    _torrentday_irc: &torrentday_irc
      passkey: '{? torrentday.rss_key ?}'
      nickname: '{? torrentday.nickname ?}'
      password: '{? torrentday.irc_password ?}'

    _trakt_credentials: &trakt_credentials
      username: '{? trakt.username ?}'
      account: '{? trakt.account ?}'

    _tv_lookup: &tv_lookup
      thetvdb_lookup: yes
      trakt_lookup:
        <<: *trakt_credentials
  
  trakt_tv_720: &trakt_tv_720
    trakt_list:
      <<: *trakt_credentials
      list: '{? trakt.tv_720p ?}'
      type: shows

  trakt_tv_1080: &trakt_tv_1080
    trakt_list:
      <<: *trakt_credentials
      list: '{? trakt.tv_1080p ?}'
      type: shows

  global-settings:
    transmission:
      <<: *transmission
    free_space:
      path: /mnt/pi4/torrent-complete
      space: 2000
    include:
      - reject.yml
    sort_by:
      field: quality
      reverse: yes

tasks:
  irc-tv-dl:
    manual: yes
    max_reruns: 0
    template:
      - global-settings
    content_size:
      max: 3000
      min: 500
    sequence:
      - configure_series:
          from:
            <<: *trakt_tv_720
          settings:
            exact: no
            target: 720p hdtv+
            quality: 720p webrip+
            timeframe: 18 hours
            identified_by: ep
            specials: no
      - configure_series:
          from:
            <<: *trakt_tv_1080
          settings:
            exact: no
            target: 1080p hdtv+
            quality: 1080p webrip+
            timeframe: 18 hours
            identified_by: ep
            specials: no

irc:
  irc_td:
    <<: *torrentday_irc
    tracker_file: 'trackers/TorrentDay.tracker'
    port: 6697
    use_ssl: yes
    channels: ["#td.announce"]
    task_re:
      - task: irc-tv-dl
        patterns:
          - regexp: (TV\/x264|TV\/Web-DL)
            field: irc_category

web_server:
  web_ui: yes
